name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare tag name
      run: |
           echo "::set-env name=IMAGE_TAG::movex/bundler-audit-image:${GITHUB_RUN_NUMBER}_$(date +%s)"
           echo "::set-env name=IMAGE_TAG_LATEST::movex/bundler-audit-image"
    - name: Build the Docker image
      run: >-
           docker build . --file Dockerfile --label GITHUB_REF=${GITHUB_REF}
           --label GITHUB_SHA=${GITHUB_SHA} --tag "${IMAGE_TAG_LATEST}"
    # Use credentials manager for docker. For installation hints see
    # https://github.com/docker/docker-credential-helpers/issues/102
    - name: Update OS package repository and install credentials manager, build tools, gpg2
      run: |
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends pass build-essential gnupg2
    - name: Install go for building docker-credential-helpers
      run: sudo snap install --classic go
    - name: Set GOPATH
      run: echo "::set-env name=GOPATH::${HOME}/go"
    - name: Get docker-credential-helpers source
      run: go get github.com/docker/docker-credential-helpers
      # Ignore "no Go files"
      continue-on-error: true
    - name: Build docker-credential-helpers
      run: |
           cd "${GOPATH}/src/github.com/docker/docker-credential-helpers"
           make pass
    - name: Put docker-credential-pass into $PATH
      run: >-
           sudo cp
           "${GOPATH}/src/github.com/docker/docker-credential-helpers/bin/docker-credential-pass"
           /usr/local/bin

    - name: Generate gpg2 key
      env:
        GPG_PASS: ${{ secrets.GPG_PASS }}
      run: |
           cat <<EOF |
           %echo Generating a basic OpenPGP key
           Key-Type: default
           Subkey-Type: default
           Name-Real: CICD Deployer
           Name-Comment: User for docker push to docker hub
           Name-Email: cicd@foo.bar
           Expire-Date: 0
           Passphrase: ${GPG_PASS}
           %commit
           EOF
           gpg2 --batch --gen-key

    - name: Initialize pass using the created key
      env:
        DOCKER_PASS_INITIALIZED_CHECK_PASS: ${{ secrets.DOCKER_PASS_INITIALIZED_CHECK_PASS }}
      run: |
           echo "gpg keys:"
           gpg --list-keys
           echo "gpg secret keys:"
           gpg --list-secret-keys
           echo "gpg2 keys:"
           gpg2 --list-keys
           echo "gpg2 secret keys:"
           gpg2 --list-secret-keys
           pass init "cicd@foo.bar"
           pass insert --echo docker-credential-helpers/docker-pass-initialized-check <<< "${DOCKER_PASS_INITIALIZED_CHECK_PASS}"
           # echo "check docker-pass-initialized-check"
           # pass show docker-credential-helpers/docker-pass-initialized-check
           # docker-credential-pass list
    - name: Configure docker credentials store
      run: |
           mkdir -p ${HOME}/.docker && cat >${HOME}/.docker/config.json <<EOF
           {
             "credsStore": "pass"
           }
           EOF

    - name: Login to the docker registry and push
      env:
        HUB_DOCKER_TOKEN: ${{ secrets.HUB_DOCKER_PASS }}
      run: |
           docker login --username movex --password-stdin <<< "${HUB_DOCKER_TOKEN}"
           docker-credential-pass list
           docker push "${IMAGE_TAG_LATEST}"
