name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare tag name
      run: echo "::set-env name=IMAGE_TAG::movex/bundler-audit-image:${GITHUB_RUN_NUMBER}_$(date +%s)"
    - name: Build the Docker image
      run: >-
           docker build . --file Dockerfile --label GITHUB_REF=${GITHUB_REF}
           --label GITHUB_SHA=${GITHUB_SHA} --tag "${IMAGE_TAG}"
    # Use credentials manager for docker. For installation hints see
    # https://github.com/docker/docker-credential-helpers/issues/102
    - name: Update OS package repository
      run: sudo apt-get update
    - name: Install credentials manager
      run: sudo apt-get install -y --no-install-recommends pass build-essential
    - name: Install go for building docker-credential-helpers
      run: sudo snap install --classic go
    - name: Set GOPATH
      run: echo "::set-env name=GOPATH::${HOME}/go"
    # Ignore "no Go files"
    - name: Get docker-credential-helpers source
      run: go get github.com/docker/docker-credential-helpers
      continue-on-error: true
    - name: Build docker-credential-helpers
      run: >-
           cd "${GOPATH}/src/github.com/docker/docker-credential-helpers" &&
           make pass
    - name: Put docker-credential-pass into $PATH
      run: >-
           sudo cp
           "${GOPATH}/src/github.com/docker/docker-credential-helpers/bin/docker-credential-pass"
           /usr/local/bin

    - name: Generate gpg2 key
      env:
        GPG_PASS: ${{ secrets.GPG_PASS }}
      run: >-
           cat << EOF |
           %echo Generating a basic OpenPGP key
           Key-Type: default
           Subkey-Type: default
           Name-Real: CICD Deployer
           Name-Comment: User for docker push to docker hub
           Name-Email: cicd@foo.bar
           Expire-Date: 0
           Passphrase: ${GPG_PASS}
           %commit
           EOF
           gpg2 --batch --gen-key

    - name: Initialize pass using the created key
      run: pass init "cicd@foo.bar"
    - name: Configure docker credentials store
      run: >-
           cat >${HOME}/.docker/config.json << EOF
           {
             "credsStore": "pass"
           }
           EOF

    - name: Login to the docker registry
      env:
        HUB_DOCKER_TOKEN: ${{ secrets.HUB_DOCKER_PUSH_BUNDLER_AUDIT_IMAGE_TOKEN }}
      run: >-
           cat <<< "${HUB_DOCKER_TOKEN}" |
           docker login --username movex --password-stdin

    - name: Push to docker hub
      run: docker push "${IMAGE_TAG}"
