name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --label GITHUB_REF=${GITHUB_REF} --label GITHUB_SHA=${GITHUB_SHA} --tag movex/bundler-audit-image:${GITHUB_RUN_NUMBER}_$(date +%s)
